FROM node:carbon-alpine as dist
WORKDIR /tmp/
COPY package.json yarn.lock tsconfig.json ./
COPY src/ src/
RUN yarn install --pure-lockfile
RUN yarn run build

FROM node:carbon-alpine as node_modules
WORKDIR /tmp/
COPY package.json yarn.lock ./
RUN yarn install --pure-lockfile --prod

FROM node:carbon-alpine
WORKDIR /tmp/
COPY --from=node_modules /tmp/node_modules ./node_modules
COPY --from=dist /tmp/dist ./dist
CMD ["node", "dist/main.js"]
EXPOSE 3001